# Generated by Django 3.0.8 on 2020-07-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insititucion',
            new_name='Institucion',
        ),
    ]
