# Generated by Django 3.0.8 on 2020-07-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='curricula.Anio'),
        ),
    ]
