# Generated by Django 3.0.8 on 2020-07-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_auto_20200713_1302'),
        ('curricula', '0003_auto_20200713_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='materia',
        ),
        migrations.CreateModel(
            name='MateriaEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField(blank=True)),
                ('fecha_hasta', models.DateField(blank=True)),
                ('institucion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instituciones.Institucion')),
            ],
            options={
                'permissions': [('list_anio_lectivo', 'Puede listar años lectivos')],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='materia_evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='curricula.MateriaEvaluacion'),
        ),
    ]
