# Generated by Django 3.0.8 on 2020-07-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_auto_20200722_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
