# Generated by Django 3.1 on 2020-09-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0008_auto_20200725_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aniolectivo',
            options={'permissions': [('list_aniolectivo', 'Puede listar años lectivos'), ('actual_aniolectivo', 'Puede ver el año lectivo actual')]},
        ),
    ]
