# Generated by Django 3.0.8 on 2020-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_auto_20200907_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
