# Generated by Django 3.0.8 on 2020-07-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('createadmin_user', 'Can create users with group Admin'), ('list_user', 'Can list all users'), ('status_user', 'Can re-activate a deleted User'), ('change_other_user', 'Can edit other users info')]},
        ),
    ]
