# Generated by Django 3.0.8 on 2020-07-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200712_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('createadmin_user', 'Can create users with group Admin'), ('status_user', 'Can change status of User'), ('change_other_user', 'Can edit other users info')]},
        ),
    ]
