# Generated by Django 3.0.8 on 2020-08-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200807_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('createadmin_user', 'Can create users with group Admin'), ('status_user', 'Can change status of User'), ('change_other_user', 'Can edit other users info')], 'verbose_name': 'user', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
