# Generated by Django 3.1 on 2020-08-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200807_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil'),
        ),
    ]
