# Generated by Django 3.1 on 2020-08-29 03:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200813_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[users.models.validate_name], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[users.models.validate_name], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[users.models.validate_phone], verbose_name='Teléfono'),
        ),
    ]
