# Generated by Django 3.1 on 2020-08-28 03:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200813_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[users.models.validate_name], verbose_name='Nombre'),
        ),
    ]
