version: '3.7'



services:

    web:

        build: .

        command: python /code/manage.py runserver 0.0.0.0:8000

        volumes: 

            - .:/code

        ports: 

            - 8000:8000

        depends_on:

            - db
    
    worker:

        build: .

        command: python /code/manage.py rqworker default

        volumes: 

            - .:/code

        depends_on:

            - db

    redis:
        image: redis

        command: redis-server --requirepass redis_ontrack

        ports:

            - "6379:6379"

        volumes:

            - redis-data:/var/lib/redis
            - redis.conf:/usr/local/etc/redis/redis.conf

        environment:

            - REDIS_REPLICATION_MODE=master

    db:
        image: postgres:12.3

        environment: 
        
            POSTGRES_HOST_AUTH_METHOD: "trust"

        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data:
    redis-data:
    redis.conf:
