# Generated by Django 3.1 on 2020-08-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('alcanzada', models.BooleanField(blank=True)),
            ],
            options={
                'permissions': [('list_alumno_objetivo', 'Puede listar alumno_objetivo')],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_objetivo_cuantitativo', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('list_objetivo', 'Puede listar objetivos')],
            },
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuantitativo', models.BooleanField(blank=True)),
                ('multiple', models.BooleanField(blank=True)),
                ('valor_minimo', models.FloatField(blank=True, null=True)),
                ('valor_maximo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'permissions': [('list_tipo_objetivo', 'Puede listar tipo_objetivo')],
            },
        ),
    ]
