# Generated by Django 3.1 on 2020-08-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0001_initial'),
        ('seguimientos', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='seguimiento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientos.seguimiento'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='tipo_objetivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipoobjetivo'),
        ),
        migrations.AddField(
            model_name='alumnoobjetivo',
            name='alumno_curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnocurso'),
        ),
        migrations.AddField(
            model_name='alumnoobjetivo',
            name='objetivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.objetivo'),
        ),
    ]
