# Generated by Django 3.1 on 2020-09-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0002_auto_20200816_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivo',
            options={'permissions': [('list_objetivo', 'Puede listar objetivos'), ('create_multiple_objetivo', 'Puede crear multiples objetivos')]},
        ),
    ]
