# Generated by Django 3.1 on 2020-09-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0003_auto_20200907_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoobjetivo',
            options={'permissions': [('list_tipo_objetivo', 'Puede listar tipo_objetivo')], 'verbose_name': 'Tipo de Objetivo', 'verbose_name_plural': 'Tipos de Objetivos'},
        ),
    ]
