# Generated by Django 3.0.8 on 2020-10-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_auto_20200908_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoobjetivo',
            name='fecha_relacionada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
