# Generated by Django 3.0.8 on 2020-10-20 21:59

from django.db import migrations, models
import objetivos.models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_auto_20200908_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoobjetivo',
            options={'ordering': ['fecha_relacionada'], 'permissions': [('list_alumno_objetivo', 'Puede listar alumno_objetivo')]},
        ),
        migrations.AddField(
            model_name='alumnoobjetivo',
            name='fecha_calculo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnoobjetivo',
            name='fecha_relacionada',
            field=models.DateField(blank=True, default=objetivos.models.default_fecha),
        ),
    ]
