# Generated by Django 3.0.8 on 2020-10-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0007_auto_20201017_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoobjetivo',
            options={'ordering': ['fecha_relacionada'], 'permissions': [('list_alumno_objetivo', 'Puede listar alumno_objetivo')]},
        ),
    ]
