# Generated by Django 3.0.8 on 2020-07-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0007_delete_alumno'),
        ('instituciones', '0003_auto_20200713_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('legajo', models.CharField(blank=True, max_length=150, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('institucion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instituciones.Institucion')),
            ],
            options={
                'permissions': [('list_alumno', 'Puede listar alumnos')],
            },
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.AnioLectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.Curso')),
            ],
            options={
                'permissions': [('list_alumnocurso', 'Puede listar alumnocurso')],
            },
        ),
    ]
