# Generated by Django 3.1 on 2020-08-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnocurso',
            options={'permissions': [('list_alumnocurso', 'Puede listar alumnocurso'), ('create_multiple_alumnocurso', 'Puede crear multiples alumnocurso')]},
        ),
    ]
