# Generated by Django 3.1 on 2020-08-29 03:46

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20200828_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnocurso',
            options={'permissions': [('list_alumnocurso', 'Puede listar alumnocurso'), ('create_multiple_alumnocurso', 'Puede crear multiples alumnocurso')]},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, validators=[alumnos.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, validators=[alumnos.models.validate_name]),
        ),
    ]
