# Generated by Django 3.0.8 on 2020-10-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20200829_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnocurso',
            options={'permissions': [('list_alumnocurso', 'Puede listar alumnocurso'), ('list_evaluaciones_alumnocurso', 'Puede listar alumnocurso con evaluaciones'), ('create_multiple_alumnocurso', 'Puede crear multiples alumnocurso'), ('delete_multiple_alumnocurso', 'Puede borrar multiples alumnocurso')]},
        ),
    ]
