# Generated by Django 3.0.8 on 2020-10-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacionadjunto',
            name='url',
        ),
        migrations.AddField(
            model_name='actualizacionadjunto',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
