# Generated by Django 3.0.8 on 2020-10-02 02:55

import actualizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0002_auto_20201002_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionadjunto',
            name='file',
            field=models.FileField(upload_to=actualizaciones.models.seguimiento_file_path),
        ),
    ]
