# Generated by Django 3.0.8 on 2020-10-02 03:15

import actualizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0003_auto_20201002_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionadjunto',
            name='file',
            field=models.FileField(upload_to=actualizaciones.models.seguimiento_file_path, validators=[actualizaciones.models.validate_file_size]),
        ),
    ]
