# Generated by Django 3.0.8 on 2020-10-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0005_auto_20201012_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionadjunto',
            name='file_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actualizacionadjunto',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actualizacionadjunto',
            name='upload_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
