# Generated by Django 3.0.8 on 2020-10-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0005_auto_20201012_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualizacion',
            options={'permissions': [('list_actualizacion', 'Puede listar actualizaciones'), ('list_latest_actualizacion', 'Puede listar las ultimas actualizaciones')]},
        ),
    ]
