# Generated by Django 3.0.8 on 2020-10-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actualizaciones", "0006_auto_20201014_0154"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actualizacion",
            options={
                "permissions": [
                    ("list_actualizacion", "Puede listar actualizaciones"),
                    (
                        "list_latest_actualizacion",
                        "Puede listar las ultimas actualizaciones",
                    ),
                ]
            },
        ),
    ]
