# Generated by Django 3.0.8 on 2020-10-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0006_auto_20201014_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionadjunto',
            name='file_size',
            field=models.IntegerField(blank=True),
        ),
    ]
