# Generated by Django 3.0.8 on 2020-11-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0007_auto_20201014_0526'),
        ('actualizaciones', '0007_auto_20201015_0301'),
    ]

    operations = [
    ]
