# Generated by Django 3.0.8 on 2020-10-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizaciones', '0007_auto_20201014_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionadjunto',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
