# Generated by Django 3.0.8 on 2020-07-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('pais', models.CharField(blank=True, max_length=250)),
                ('identificador', models.CharField(blank=True, max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['fecha_creacion'],
                'permissions': [('status_institucion', 'Cambiar el estado Instituciones'), ('list_institucion', 'Puede listar Instituciones')],
            },
        ),
    ]
