# Generated by Django 3.0.8 on 2020-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
