# Generated by Django 3.0.8 on 2020-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_auto_20200713_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
