# Generated by Django 3.0.8 on 2020-07-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_auto_20200710_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['fecha_creacion'], 'permissions': [('alta_institucion', 'Puede dar de alta Institucion'), ('list_institucion', 'Puede listar Instituciones')]},
        ),
    ]
