# Generated by Django 3.0.8 on 2020-08-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_auto_20200713_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['fecha_creacion'], 'permissions': [('status_institucion', 'Cambiar el estado Instituciones'), ('list_institucion', 'Puede listar Instituciones')], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterField(
            model_name='institucion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='pais',
            field=models.CharField(blank=True, max_length=250, verbose_name='País'),
        ),
    ]
