# Generated by Django 3.0.8 on 2020-07-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_auto_20200710_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['fecha_creacion'], 'permissions': [('status_institucion', 'Cambiar el estado Instituciones'), ('list_institucion', 'Puede listar Instituciones')]},
        ),
    ]
