# Generated by Django 3.0.8 on 2020-08-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0004_auto_20200807_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['fecha_creacion'], 'permissions': [('status_institucion', 'Cambiar el estado Instituciones'), ('list_institucion', 'Puede listar Instituciones')], 'verbose_name_plural': 'Instituciones'},
        ),
    ]
