# Generated by Django 3.1 on 2020-09-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0006_auto_20200829_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='cuit',
        ),
    ]
