# Generated by Django 3.1 on 2020-08-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
    ]
