# Generated by Django 3.1 on 2020-08-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integranteseguimiento',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
    ]
