# Generated by Django 3.1 on 2020-08-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0002_auto_20200826_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integranteseguimiento',
            name='fecha_desde',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='integranteseguimiento',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='seguimientos.seguimiento'),
        ),
    ]
