# Generated by Django 3.1 on 2020-09-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0003_auto_20200826_0314'),
        ('seguimientos', '0002_auto_20200817_0216'),
    ]

    operations = [
    ]
