# Generated by Django 3.1 on 2020-09-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0004_auto_20200829_0346'),
        ('seguimientos', '0004_merge_20200906_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitudSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=256)),
            ],
            options={
                'permissions': [('list_estadosolicitudseguimiento', 'Listar estados de Solicitud de Seguimiento')],
            },
        ),
        migrations.AlterModelOptions(
            name='integranteseguimiento',
            options={'permissions': [('list_integranteseguimiento', 'Listar Integrate de Seguimiento')]},
        ),
        migrations.AlterModelOptions(
            name='rolseguimiento',
            options={'permissions': [('list_rolseguimiento', 'Listar integrante de seguimiento')]},
        ),
        migrations.CreateModel(
            name='SolicitudSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_solicitud', models.TextField(null=True)),
                ('alumnos', models.ManyToManyField(to='alumnos.AlumnoCurso')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('list_solicitudseguimiento', 'Listar Solciitudes de Seguimiento')],
            },
        ),
        migrations.CreateModel(
            name='FechaEstadoSolicitudSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientos.estadosolicitudseguimiento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientos.solicitudseguimiento')),
            ],
            options={
                'permissions': [('list_fechaestadosolicitudseguimiento', 'Listar Fechas de Estado Solicitud de Seguimiento')],
            },
        ),
    ]
