# Generated by Django 3.1 on 2020-09-10 03:10

from django.db import migrations


def create_estados(apps, schema_editor):
    EstadoSolicitudSeguimiento = apps.get_model(
        "seguimientos", "EstadoSolicitudSeguimiento"
    )
    estados = ["Pendiente", "Aceptada", "Rechazada"]
    for estado in estados:
        e = EstadoSolicitudSeguimiento.objects.create(nombre=estado)
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ("seguimientos", "0005_auto_20200910_0310"),
    ]

    operations = [
        migrations.RunPython(create_estados),
    ]
