# Generated by Django 3.1 on 2020-09-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0006_auto_20200910_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaestadosolicitudseguimiento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='seguimientos.solicitudseguimiento'),
        ),
    ]
