# Generated by Django 3.1 on 2020-09-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0007_auto_20200913_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaestadosolicitudseguimiento',
            options={'ordering': ['fecha'], 'permissions': [('list_fechaestadosolicitudseguimiento', 'Listar Fechas de Estado Solicitud de Seguimiento')]},
        ),
    ]
