# Generated by Django 3.1 on 2020-09-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0008_auto_20200913_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudseguimiento',
            options={'permissions': [('list_solicitudseguimiento', 'Listar Solciitudes de Seguimiento'), ('status_solicitudseguimiento', 'Cambiar el estado de Solciitudes de Seguimiento')]},
        ),
    ]
