# Generated by Django 3.0.8 on 2020-09-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0009_auto_20200913_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['fecha_creacion'], 'permissions': [('status_seguimiento', 'Cambiar el estado de seguimiento'), ('list_seguimiento', 'Listar seguimiento'), ('unique_seguimiento', 'Verificar que un Seguimiento tenga nombre unico')], 'verbose_name_plural': 'Seguimientos'},
        ),
    ]
