# Generated by Django 3.0.8 on 2020-07-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaAnioLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno_curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.AlumnoCurso')),
            ],
            options={
                'permissions': [('list_asistenciaaniolectivo', 'Puede listar asistencia_anio_lectivo')],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('asistio', models.FloatField(blank=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno_curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.AlumnoCurso')),
            ],
            options={
                'permissions': [('list_asistencia', 'Puede listar asistencias')],
            },
        ),
    ]
