# Generated by Django 3.0.8 on 2020-07-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'permissions': [('list_asistencia', 'Puede listar asistencias'), ('create_multiple_asistencia', 'Puede crear multiples asistencias')]},
        ),
    ]
