# Generated by Django 3.0.8 on 2020-07-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0008_auto_20200725_0319'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('puntaje', models.FloatField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('evaluacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curricula.Evaluacion')),
            ],
            options={
                'permissions': [('list_calificacion', 'Puede listar calificaciones')],
            },
        ),
    ]
