# Generated by Django 3.0.8 on 2020-08-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_auto_20200730_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'permissions': [('list_calificacion', 'Puede listar calificaciones'), ('create_multiple_calificacion', 'Puede listar calificaciones'), ('destroy_multiple_calificacion', 'Puede eliminar muchas calificaciones')]},
        ),
    ]
