# Generated by Django 3.0.8 on 2020-08-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('curricula', '0008_auto_20200725_0319'),
        ('calificaciones', '0003_auto_20200802_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionAnioLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('promedio', models.FloatField(blank=True)),
                ('alumno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('anio_lectivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curricula.AnioLectivo')),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curricula.Materia')),
            ],
            options={
                'permissions': [('list_calificacion_anio_lectivo', 'Puede listar CalificacionAnioLectivo')],
            },
        ),
    ]
