# Generated by Django 3.0.8 on 2020-08-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_calificacionaniolectivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionAnioLectivo',
        ),
    ]
