# Generated by Django 3.0.8 on 2020-08-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_auto_20200804_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'permissions': [('list_calificacion', 'Puede listar calificaciones'), ('create_multiple_calificacion', 'Puede listar calificaciones'), ('destroy_multiple_calificacion', 'Puede eliminar muchas calificaciones'), ('promedio_calificacion', 'Puede solicitar promedio de calificaciones'), ('notafinal_calificacion', 'Puede solicitar notas finales')]},
        ),
    ]
